services:
  web:
    container_name: web-container
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped